// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgbhv43Qxp-Zuzbna8smFx7D6aJ6DB3ZM',
    appId: '1:1040806092092:web:63206f6483fcc36bf61239',
    messagingSenderId: '1040806092092',
    projectId: 'gr07-skillswap-fall-2025-b387a',
    authDomain: 'gr07-skillswap-fall-2025-b387a.firebaseapp.com',
    storageBucket: 'gr07-skillswap-fall-2025-b387a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACuB4dAFJFjqnJ27aIrY_NJFozqxw8hx4',
    appId: '1:1040806092092:android:4e763a58c3282b2df61239',
    messagingSenderId: '1040806092092',
    projectId: 'gr07-skillswap-fall-2025-b387a',
    storageBucket: 'gr07-skillswap-fall-2025-b387a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb-MEFJAMs3Zertk99GRUY0BJEF_hISFI',
    appId: '1:1040806092092:ios:5c204b07e776cf3bf61239',
    messagingSenderId: '1040806092092',
    projectId: 'gr07-skillswap-fall-2025-b387a',
    storageBucket: 'gr07-skillswap-fall-2025-b387a.firebasestorage.app',
    iosBundleId: 'com.example.gr07Skillswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb-MEFJAMs3Zertk99GRUY0BJEF_hISFI',
    appId: '1:1040806092092:ios:5c204b07e776cf3bf61239',
    messagingSenderId: '1040806092092',
    projectId: 'gr07-skillswap-fall-2025-b387a',
    storageBucket: 'gr07-skillswap-fall-2025-b387a.firebasestorage.app',
    iosBundleId: 'com.example.gr07Skillswap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgbhv43Qxp-Zuzbna8smFx7D6aJ6DB3ZM',
    appId: '1:1040806092092:web:845ad8cb8c0ca799f61239',
    messagingSenderId: '1040806092092',
    projectId: 'gr07-skillswap-fall-2025-b387a',
    authDomain: 'gr07-skillswap-fall-2025-b387a.firebaseapp.com',
    storageBucket: 'gr07-skillswap-fall-2025-b387a.firebasestorage.app',
  );
}
